version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform --version
      - terraform init
      - terraform plan 
      - terraform apply --auto-approve
        # BELOW COMMAND IS FOR DESTRYOING THE TERRAFORM
      - terraform destroy --auto-approve

