version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre Build Phase"

  build:
    commands:
      - echo "Build Phase"
      # Place any additional build steps here

  post_build:
    commands:
      - echo "Post Build Phase"
      # Place any additional post-build steps here
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform Installed"
      - terraform init -input=false

artifacts:
  files:
    - '**/*'
  discard-paths: yes

post_build:
  commands:
    - terraform apply -auto-approve
    - terraform destroy -auto-approve
