version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0  # Replace with your desired Terraform version
    commands:
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'

